[project]
name = "aim-unicorn"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sejin Kim <hello@sejin.kim>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[system-requirements]
linux="3.10.0"

[tasks]
imgtools = "pip install --no-build-isolation --disable-pip-version-check -e /cluster/home/sejinkim/pkgs/med-imagetools"

[environments]
default = ["base"]
surv = ["survival"]

[dependencies]
python = "3.10.*"
python-dotenv = ">=1.0.1,<1.1"
poetry = ">=1.8.3,<1.9"

[feature.base.pypi-dependencies]
project-lighter = { version = "==0.0.2a19" }
foundation-cancer-image-biomarker = { version = "==1.0.0" }

[feature.survival.dependencies]
r-base = ">=4.1.3,<4.4"
lifelines = ">=0.9.4,<0.28"
rpy2 = ">=3.5.11,<3.6"
r-mrmre = ">=2.1.2.1,<2.1.3"
r-essentials = ">=4.1,<5"
