[project]
name = "readii-fmcib"
version = "0.1.0"
description = "Code to run READII negative controls through FMCIB"
authors = ["Sejin Kim <hello@sejin.kim>", "Katy Scott <k.l.scott16@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
kernel = "ipython kernel install --name=readii_fmcib --display-name=readii_fmcib --user"

[environments]
fmcib = {features = ["fmcib"], no-default-feature = true}

[dependencies]
python = "3.12.*"
ipykernel = ">=6.29.5,<7"
pip = ">=24.3.1,<25"
numpy = "1.26.4.*"
python-dotenv = ">=1.0.1,<2"
ipywidgets = ">=8.1.5,<9"

[pypi-dependencies]
readii = ">=1.26.0, <2"
med-imagetools = ">=1.10.1, <2"

############################################## FMCIB ################################################

[feature.fmcib.dependencies]
python = "3.10.*"
ipykernel = ">=6.29.5,<7"
pip = ">=23.3.2,<24"
python-dotenv = ">=1.0.1,<2"
joblib = ">=1.4.2,<2"

[feature.fmcib.pypi-dependencies]
project-lighter = { version = "==0.0.2a19" }
foundation-cancer-image-biomarker = ">=1.0.0, <2"
med-imagetools = ">=1.2.0.2, <2"

[feature.fmcib.tasks.fmcib_kernel]
cmd = "ipython kernel install --name=fmcib --display-name=fmcib --user"
description = "Create Jupyter kernel for running FMCIB inference in Jupyter notebook. Will install in .pixi directory."